@startuml chain

box "Carbon Market Channel" #LightBlue
participant "Hydrogen Certification Smart Contract" as HC
participant "Carbon Token Smart Contract" as CM
end box

HC -> CM: Report Carbon Production
activate CM
note left: Certification scheme such as CertifHy

alt user has sufficient tokens

    CM -> HC: Tokens for user are spent

else insufficient tokens

    CM -> HC: Smart contract records a carbon debt
end

deactivate CM

@enduml