@startuml chain

box "Carbon Market Channel" #LightBlue
participant "Hydrogen Producer Registrar Smart Contract" as HC
participant "Carbon Token Smart Contract" as CM
end box

HC -> CM: Issue Hydrogen Producer
activate CM
note left: Registrar can be a government agency or official institution

alt Small Hydrogen Producer

    CM -> HC: 1000 tokens

else Medium Hydrogen Producer

    CM -> HC: 5000 tokens
else Large Hydrogen Producer

    CM -> HC: 1000 tokens
end

deactivate CM

@enduml