@startuml SequenceNormal
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor "Hydrogen Producer" as User
participant "Carbon Market Website" as A
participant "HTTP API" as B
participant "Carbon Market Fabric Channel" as C

User -> A: Market Operation
activate A

A -> B: Create Request
activate B

B -> C: Blockchain Operation
activate C
C --> B: WorkDone
deactivate C

B --> A: Request Created
deactivate B

A --> User: Done
deactivate A

@enduml