@startuml SequenceNormal
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor "Hydrogen Producer" as User
participant "Carbon Market Website" as A
participant "HTTP API" as B
box "Carbon Market Channel" #LightBlue
participant "Carbon Market Smart Contract" as C
participant "Carbon Token Smart Contract" as D
end box

User -> A: Market Operation
activate A

A -> B: Create Request
activate B

B -> C: Blockchain Operation
activate C
alt Token Operations - exhange, burn, ...
C -> D: Token Operation
activate D
D --> C: Work Done
deactivate D
end
C --> B: Work Done
deactivate C

B --> A: Request Created
deactivate B

A --> User: Done
deactivate A

@enduml